# Sudoku Game


The rules of sudoku state that each row, column, and nonant must contain unique symbols; typically, the numbers 1 through 9.

Through deduction and abstract reasoning, the player must fill in the blank spaces using logic based on the pre-populated symbols in the grid.

The goal of this project is to create the basis for the game of sudoku in Python:
    - viewable as a grid
    - 



Secondarily, I'd like to examine the following potentials:

    - solve all existing game boards (that are solvable *logically*)
    - qualify the methodology by which players are able to solve the game:
        - using abstract reasoning across the whole game board
        - define techniques?
        
As well as:
    - be able to quantify the difficulty of a given game state

## Implementation Details
- Each cell 'eliminates' the others in their respective row, column, and nonant when the value is imputed
- Grid creation should imply the solve, for solvable boards?

In [2]:
#from src.cell import Cell
from src.grids import hard_game
#from src.nine_cell import NineCell, Row, Column, Nonant
from src.sudoku_grid import  SudokuGrid

ModuleNotFoundError: No module named 'pandas'

## Sudoku Graph Network Demonstration

In [2]:
a = SudokuGrid()
hard_game(a)
print(a.total_trues)
a.show_grid

28

   1  2  3  4  5  6  7  8  9
1              4  9  6
2  3     4        6  1     9
3     2           1     3  4
4     1  2        4
5  4        5              6
6     8        2  9
7        1  6           2
8           9              8
9     6              3

### Adding in exlusion logic

Let's try to make some rules which can fill cells based on various strategies.

In [3]:
a = SudokuGrid()
hard_game(a)


# make it a dataframe
        # return pd.DataFrame(np.array([x.nonant.nonant for x in self.cells]).reshape(9,9), index=range(1,10), columns=range(1,10))

In [4]:
a.nonants[-1].assign_laterals()

#horizontals

In [5]:
a.show_grid

   1  2  3  4  5  6  7  8  9
1              4  9  6
2  3     4        6  1     9
3     2           1     3  4
4     1  2        4
5  4        5              6
6     8        2  9
7        1  6           2
8           9              8
9     6              3

In [14]:
nonant_verticals = a.nonants[8].verticals
from itertools import chain
for idx, x in enumerate(nonant_verticals):

    this_vert = set(chain.from_iterable([x.possible for x in nonant_verticals[idx]]))

    others = nonant_verticals.copy()
    del(others[idx])
    # for y in others:
    #     for x in y:
    #         print(x.possible)
    others = set(chain.from_iterable([y.possible for y in x for x in others]))

    #print(this_vert.difference(others))
    print(this_vert, others)

{3, 4, 5, 7, 9} {3, 4, 5, 7, 9}
{1, 2, 4, 5, 6, 7, 9} {1, 2, 4, 5, 6, 7, 9}
{8, 1, 5, 7} {8, 1, 5, 7}

In [11]:
a.show_grid

   1  2  3  4  5  6  7  8  9
1              4  9  6
2  3     4        6  1     9
3     2           1     3  4
4     1  2        4
5  4        5              6
6     8        2  9
7        1  6           2
8           9              8
9     6              3

In [43]:
def show_pressure(grid, number):
# show a 9x9 grid which implies pressure based on a specific number

    for cell in [x for x in grid.cells if x.value == number]:
        for nine_p in [cell.row, cell.column, cell.nonant]:
            for x in nine_p.cells:
                x.pressure = number 

show_pressure(a, 6)
a.show_grid

### implement a recursive algorithm to check each row, column, and nonant successively until the puzzle is solved
### recursive generally will work better with a depth-first approach; a stack
# stack = []


    # check 3 rows, 3 columns, 1 quadrant for 'pressure'


    # check all row, column, and nonant eliminations from grid to determine the state of the current nine piece
    
    # call it back on itself if the state changes at all

    # call it back on any found number

    # have a 'slow mode' to show the resolution of the stack.

   1  2  3  4  5  6  7  8  9
1              4  9  6
2  3     4        6  1     9
3     2           1     3  4
4     1  2        4
5  4        5              6
6     8        2  9
7        1  6           2
8           9              8
9     6              3

In [44]:
a.show_grid

   1  2  3  4  5  6  7  8  9
1              4  9  6
2  3     4        6  1     9
3     2           1     3  4
4     1  2        4
5  4        5              6
6     8        2  9
7        1  6           2
8           9              8
9     6              3